"""A2, deel 1 — het perfectum, de verleden tijd en bijzinnen."""

from _kit import (concept, lesson, module, ex, wrong, pattern, discover, rule,
                  mc, dehet, nietgeen, pickorder, pick2, dialogue, scenario,
                  blank, conjugate, transform, fa2nl, fix, type_all,
                  order, question, subclause)

# ---------------------------------------------------------------- concepts

C_PERF = concept(
    "perfect-regular", "Perfectum met regelmatige deelwoorden", "ماضی نقلی با فعل باقاعده", "A2",
    keywords=["perfectum", "voltooid deelwoord", "gewerkt", "gemaakt", "ماضی نقلی"],
    summary_fa="hebben/zijn + ge…t/d آخر جمله. قاعده‑ی 't kofschip تعیین می‌کند t یا d.")

C_PERF_IRR = concept(
    "perfect-irregular", "Onregelmatige deelwoorden", "اسم مفعول بی‌قاعده", "A2",
    keywords=["gezien", "gegeten", "gedronken", "geschreven", "onregelmatig deelwoord"],
    summary_fa="اغلب ge…en: zien → gezien، drinken → gedronken. باید حفظ شوند.")

C_PERF_AUX = concept(
    "perfect-auxiliary", "Hebben of zijn?", "hebben یا zijn در ماضی نقلی", "A2",
    keywords=["hebben zijn", "ben gegaan", "heb gewerkt", "hulpwerkwoord"],
    summary_fa="حرکت و تغییر حالت با zijn؛ بقیه با hebben.")

C_PERF_SEP = concept(
    "perfect-separable", "Perfectum van scheidbare werkwoorden", "ماضی نقلی افعال جداشدنی", "A2",
    keywords=["opgestaan", "meegenomen", "opgebeld", "scheidbaar perfectum"],
    summary_fa="ge وسط می‌رود: opstaan → opgestaan، meenemen → meegenomen.")

C_PAST_REG = concept(
    "past-regular", "Imperfectum: -te en -de", "ماضی ساده‌ی باقاعده", "A2",
    keywords=["imperfectum", "verleden tijd", "werkte", "woonde", "ماضی ساده"],
    summary_fa="ریشه + te/ten یا de/den، بر اساس همان قاعده‌ی 't kofschip.")

C_PAST_IRR = concept(
    "past-irregular", "Onregelmatig imperfectum", "ماضی ساده‌ی بی‌قاعده", "A2",
    keywords=["was", "waren", "had", "ging", "kwam", "zei", "onregelmatig verleden"],
    summary_fa="was/waren، had/hadden، ging، kwam، zei، dacht — پرکاربردترین‌ها.")

C_PERF_VS_PAST = concept(
    "perfect-vs-past", "Perfectum of imperfectum?", "ماضی نقلی یا ماضی ساده؟", "A2",
    keywords=["perfectum imperfectum", "verschil", "wanneer", "verhaal"],
    summary_fa="در گفتار معمولاً ماضی نقلی؛ برای روایت و توصیف گذشته ماضی ساده.")

C_COORD = concept(
    "conj-coordinating", "Nevenschikkend: en, maar, want, of, dus", "حروف ربط هم‌پایه", "A2",
    keywords=["en", "maar", "want", "of", "dus", "nevenschikkend"],
    summary_fa="این پنج تا ترتیب جمله را عوض نمی‌کنند — بعدشان جمله‌ی عادی می‌آید.")

C_SUB = concept(
    "conj-subordinating", "Bijzin: werkwoord achteraan", "جمله‌واره: فعل در انتها", "A2",
    keywords=["omdat", "dat", "als", "terwijl", "bijzin", "werkwoord achteraan"],
    summary_fa="بعد از omdat، dat، als، terwijl… فعل می‌رود آخر جمله‌واره.")

C_SUB_ORDER = concept(
    "clause-order", "Hoofdzin en bijzin samen", "ترکیب جمله‌ی اصلی و جمله‌واره", "A2",
    keywords=["hoofdzin bijzin", "komma", "volgorde", "omdat ik", "ترتیب"],
    summary_fa="اگر جمله‌واره اول بیاید، کل آن «جای اول» است و فعلِ جمله‌ی اصلی بلافاصله بعدش می‌آید.")

C_INDIRECT_Q = concept(
    "indirect-question", "Indirecte vraag", "سؤال غیرمستقیم", "A2",
    keywords=["of", "weet je of", "indirecte vraag", "vraagwoord bijzin"],
    summary_fa="سؤال داخل جمله می‌رود و فعلش آخر می‌شود: Weet je of hij komt?")

# ----------------------------------------------------------------- lessons

lesson(
    "a2-l01", "a2-perfectum", "A2",
    "Ik heb gewerkt", "ماضی نقلی: ساخت پایه",
    [C_PERF],
    discover(
        ["werken → Ik heb gewerkt.", "maken → Ik heb gemaakt.",
         "wonen → Ik heb gewoond.", "leren → Ik heb geleerd."],
        "دو تا از این‌ها به t ختم شده‌اند و دو تا به d. چه فرقی بین فعل‌ها هست؟",
        "به آخرین حرفِ ریشه نگاه کن: werk و maak به k ختم می‌شوند (بی‌صدا) → t. woon و leer به n و r (باصدا) → d."),
    rule("hebben + ge…t / ge…d",
         "ریشه‌ی فعل با ge شروع و با t یا d تمام می‌شود. اگر آخرین حرفِ ریشه در «'t kofschip» باشد (t، k، f، s، ch، p) → t؛ وگرنه → d.",
         "have + past participle"),
    pattern([("Ik", "subject"), ("heb", "aux"), ("gisteren", "time"),
             ("hard", "manner"), ("gewerkt", "participle")],
            "فعل کمکی جای دوم، اسم مفعول آخرِ آخر."),
    [
        ex("Ik heb gisteren hard gewerkt.", "دیروز سخت کار کردم."),
        ex("Heb je het huiswerk gemaakt?", "تکالیف را انجام دادی؟"),
        ex("We hebben tien jaar in Iran gewoond.", "ده سال در ایران زندگی کردیم."),
        ex("Hij heeft Nederlands geleerd.", "او هلندی یاد گرفت."),
        ex("Ik heb net gebeld.", "همین الان زنگ زدم."),
    ],
    [
        wrong("Ik heb gewerkt gisteren.", "Ik heb gisteren gewerkt.",
              "اسم مفعول باید آخرین کلمه‌ی جمله باشد."),
        wrong("Ik ben gewerkt.", "Ik heb gewerkt.",
              "werken فعل حرکتی نیست، پس با hebben می‌آید."),
    ],
    "این پرکاربردترین زمانِ گذشته در گفتار هلندی است. وقتی کسی می‌پرسد «آخر هفته چه کار کردی؟»، جواب تقریباً همیشه با ماضی نقلی است.",
    [
        mc("Ik heb gisteren ___. (werken)", ["gewerkt", "gewerkd", "werkte"], "gewerkt",
           "ریشه werk به k ختم می‌شود → t.", concept=C_PERF),
        mc("We hebben in Delft ___. (wonen)", ["gewoond", "gewoont", "woonde"], "gewoond",
           "ریشه woon به n ختم می‌شود (باصدا) → d.", concept=C_PERF),
        mc("Heb je hem ___? (bellen)", ["gebeld", "gebelt", "belde"], "gebeld",
           "ریشه bel به l ختم می‌شود → d.", concept=C_PERF),
        blank("Ik heb het formulier ___. (maken)", "gemaakt",
              "maak به k ختم می‌شود → gemaakt.", concept=C_PERF),
        blank("Zij heeft veel ___. (leren)", "geleerd",
              "leer به r ختم می‌شود → geleerd.", concept=C_PERF),
        order("Ik heb gisteren hard gewerkt.",
              why="فعل کمکی جای دوم، اسم مفعول آخر.", concept=C_PERF),
        fix("Ik heb gemaakt mijn huiswerk.", "Ik heb mijn huiswerk gemaakt.",
            "اسم مفعول باید آخرین کلمه باشد.", concept=C_PERF),
        transform("Ik werk hard. → (ماضی نقلی)", "Ik heb hard gewerkt.",
                  "hebben + ge…t، و اسم مفعول آخر.", concept=C_PERF),
        fa2nl("«دیروز تکالیفم را انجام دادم.»", "Ik heb gisteren mijn huiswerk gemaakt.",
              "heb جای دوم، gemaakt آخر.", concept=C_PERF),
    ])

lesson(
    "a2-l02", "a2-perfectum", "A2",
    "Gezien, gedronken, geschreven", "اسم مفعول‌های بی‌قاعده",
    [C_PERF_IRR],
    discover(
        ["zien → gezien", "drinken → gedronken", "schrijven → geschreven",
         "eten → gegeten", "lezen → gelezen"],
        "این‌ها به چه چیزی ختم می‌شوند، نه به t/d؟",
        "به -en. بیشتر فعل‌های بی‌قاعده الگوی ge…en دارند و اغلب مصوتشان هم عوض می‌شود."),
    rule("ge… + en (met klankverandering)",
         "فعل‌های بی‌قاعده اسم مفعولشان با -en تمام می‌شود: gezien، gedronken، geschreven، gegeten، genomen.",
         "irregular participles end in -en"),
    pattern([("drinken", "inf"), ("→", "arrow"), ("gedronken", "participle"),
             ("|", "sep"), ("schrijven", "inf"), ("→", "arrow"), ("geschreven", "participle")],
            "این‌ها را باید مثل واژه یاد گرفت، نه از روی قاعده ساخت."),
    [
        ex("Ik heb die film al gezien.", "آن فیلم را قبلاً دیده‌ام."),
        ex("We hebben koffie gedronken.", "قهوه خوردیم."),
        ex("Ik heb hem een mail geschreven.", "برایش یک ایمیل نوشتم."),
        ex("Heb je al gegeten?", "غذا خورده‌ای؟"),
        ex("Ik heb de krant gelezen.", "روزنامه را خواندم."),
        ex("Zij heeft de trein genomen.", "با قطار رفت."),
    ],
    [
        wrong("Ik heb de film geziend.", "Ik heb de film gezien.",
              "zien بی‌قاعده است؛ اسم مفعولش gezien است، نه geziend."),
        wrong("Ik heb koffie gedrinkt.", "Ik heb koffie gedronken.",
              "drinken بی‌قاعده است: gedronken."),
    ],
    "بیشتر فعل‌های روزمره (خوردن، نوشیدن، دیدن، نوشتن، خواندن، گرفتن) دقیقاً همین‌هایند. بدون آن‌ها نمی‌شود درباره‌ی دیروز حرف زد.",
    [
        mc("Ik heb die film al ___. (zien)", ["gezien", "geziend", "gezient"], "gezien",
           "zien → gezien.", concept=C_PERF_IRR),
        mc("We hebben veel ___. (drinken)", ["gedronken", "gedrinkt", "gedrinken"], "gedronken",
           "drinken → gedronken (مصوت هم عوض می‌شود).", concept=C_PERF_IRR),
        mc("Heb je de brief ___? (schrijven)", ["geschreven", "geschrijft", "geschrijven"],
           "geschreven", "schrijven → geschreven.", concept=C_PERF_IRR),
        blank("Ik heb net ___. (eten)", "gegeten",
              "eten → gegeten.", concept=C_PERF_IRR),
        blank("Zij heeft de krant ___. (lezen)", "gelezen",
              "lezen → gelezen.", concept=C_PERF_IRR),
        fix("Ik heb een boek geleesd.", "Ik heb een boek gelezen.",
            "lezen بی‌قاعده است: gelezen.", concept=C_PERF_IRR),
        transform("Ik zie de film. → (ماضی نقلی)", "Ik heb de film gezien.",
                  "hebben + gezien.", concept=C_PERF_IRR),
        fa2nl("«غذا خورده‌ای؟»", "Heb je al gegeten?", 
              "در سؤال، فعل کمکی اول می‌آید و اسم مفعول آخر.", alt=["Heb je gegeten?"], concept=C_PERF_IRR),
        order("Ik heb hem een mail geschreven.",
              why="اسم مفعول آخرین کلمه است.", concept=C_PERF_IRR),
    ])

lesson(
    "a2-l03", "a2-perfectum", "A2",
    "Hebben of zijn?", "hebben یا zijn؟",
    [C_PERF_AUX],
    discover(
        ["Ik heb gewerkt.", "Ik ben naar Utrecht gegaan.",
         "Ik heb gefietst.", "Ik ben naar huis gefietst."],
        "به دو جمله‌ی آخر نگاه کن: همان فعل، ولی یکی heb و دیگری ben. چه فرقی کرده؟",
        "وقتی مقصد ذکر می‌شود (naar huis)، حرکت از جایی به جایی است → zijn. بدون مقصد، فقط «فعالیت» است → hebben."),
    rule("beweging naar een plek of verandering → zijn · anders hebben",
         "gaan، komen، worden، blijven و فعل‌های تغییر حالت همیشه zijn می‌گیرند. بقیه hebben.",
         "motion/change take zijn"),
    pattern([("Ik", "subject"), ("ben", "aux-zijn"), ("naar Amsterdam", "place"), ("gegaan", "participle"),
             ("|", "sep"), ("Ik", "subject"), ("heb", "aux-hebben"), ("gewerkt", "participle")],
            "blijven هم zijn می‌گیرد، با اینکه اصلاً حرکتی در کار نیست — استثنای مهم."),
    [
        ex("Ik ben naar de dokter geweest.", "دکتر رفتم.", "zijn → geweest، بسیار پرکاربرد"),
        ex("Hij is te laat gekomen.", "دیر آمد."),
        ex("We zijn thuis gebleven.", "خانه ماندیم."),
        ex("Ik heb de hele dag gewerkt.", "تمام روز کار کردم."),
        ex("Zij is ziek geworden.", "مریض شد.", "تغییر حالت → zijn"),
        ex("Ik ben met de trein naar Den Haag gegaan.", "با قطار به لاهه رفتم."),
    ],
    [
        wrong("Ik heb naar huis gegaan.", "Ik ben naar huis gegaan.",
              "gaan همیشه با zijn می‌آید."),
        wrong("Ik ben gewerkt.", "Ik heb gewerkt.",
              "werken فعل حرکتی یا تغییر حالت نیست → hebben."),
    ],
    "هر بار که درباره‌ی دیروز حرف می‌زنی این انتخاب را داری. یک ترفند ساده: اگر جمله «کجا رفتی؟» را جواب می‌دهد، zijn است.",
    [
        pick2("Ik ___ naar Amsterdam gegaan.", ["ben", "heb"], "ben",
              "gaan همیشه zijn می‌گیرد.", concept=C_PERF_AUX),
        pick2("Ik ___ de hele dag gewerkt.", ["heb", "ben"], "heb",
              "werken با hebben می‌آید.", concept=C_PERF_AUX),
        pick2("Zij ___ ziek geworden.", ["is", "heeft"], "is",
              "worden تغییر حالت است → zijn.", concept=C_PERF_AUX),
        pick2("We ___ thuis gebleven.", ["zijn", "hebben"], "zijn",
              "blijven استثناست و zijn می‌گیرد.", concept=C_PERF_AUX),
        mc("___ je gisteren naar de les geweest?", ["Ben", "Heb", "Was"], "Ben",
           "zijn → geweest، با فعل کمکی zijn.", concept=C_PERF_AUX),
        blank("Hij ___ te laat gekomen.", "is",
              "komen حرکت است → zijn.", concept=C_PERF_AUX),
        fix("Ik heb naar de winkel gegaan.", "Ik ben naar de winkel gegaan.",
            "gaan با zijn می‌آید.", concept=C_PERF_AUX),
        fa2nl("«دیروز دکتر رفتم.»", "Ik ben gisteren naar de dokter geweest.",
              "«جایی رفتن و برگشتن» با ben … geweest بیان می‌شود.", concept=C_PERF_AUX),
        order("Wij zijn met de auto naar Utrecht gereden.",
              why="فعل کمکی zijn جای دوم، اسم مفعول آخر.", concept=C_PERF_AUX),
    ])

lesson(
    "a2-l04", "a2-perfectum", "A2",
    "Ik ben opgestaan", "ماضی نقلی افعال جداشدنی",
    [C_PERF_SEP],
    discover(
        ["opstaan → Ik ben opgestaan.", "meenemen → Ik heb het meegenomen.",
         "opbellen → Ik heb hem opgebeld."],
        "ge کجا رفته؟",
        "وسطِ کلمه، بین پیشوند و فعل. برای همین می‌شود opgestaan، نه geopstaan."),
    rule("prefix + ge + deelwoord",
         "در فعل‌های جداشدنی، ge بین پیشوند و فعل می‌نشیند و کل کلمه یکجا آخر جمله می‌رود.",
         "prefix + ge + participle"),
    pattern([("op", "prefix"), ("ge", "infix"), ("staan", "verb"), ("→", "arrow"), ("opgestaan", "result")],
            "برخلاف جمله‌ی حال، اینجا پیشوند دیگر جدا نمی‌شود."),
    [
        ex("Ik ben vanochtend vroeg opgestaan.", "امروز صبح زود بیدار شدم."),
        ex("Heb je je paspoort meegenomen?", "پاسپورتت را آوردی؟"),
        ex("Ik heb hem gisteren opgebeld.", "دیروز بهش زنگ زدم."),
        ex("De trein is te laat aangekomen.", "قطار دیر رسید."),
        ex("We hebben het huis schoongemaakt.", "خانه را تمیز کردیم."),
    ],
    [
        wrong("Ik ben vroeg gestaan op.", "Ik ben vroeg opgestaan.",
              "در ماضی نقلی پیشوند جدا نمی‌شود؛ همه‌چیز یک کلمه می‌شود."),
        wrong("Ik heb hem geopbeld.", "Ik heb hem opgebeld.",
              "ge وسط می‌آید، نه اول."),
    ],
    "چون بیشتر فعل‌های روزمره جداشدنی‌اند، هر تعریف کردن از روزت به این نیاز دارد: بیدار شدم، زنگ زدم، رسیدم، تمیز کردم.",
    [
        mc("Ik ben vroeg ___. (opstaan)", ["opgestaan", "geopstaan", "gestaan op"], "opgestaan",
           "ge وسط کلمه می‌آید.", concept=C_PERF_SEP),
        mc("Heb je het ___? (meenemen)", ["meegenomen", "gemeenemen", "genomen mee"],
           "meegenomen", "mee + ge + nomen.", concept=C_PERF_SEP),
        blank("Ik heb hem gisteren ___. (opbellen)", "opgebeld",
              "op + ge + beld.", concept=C_PERF_SEP),
        blank("De trein is te laat ___. (aankomen)", "aangekomen",
              "aan + ge + komen، و با zijn چون حرکت است.", concept=C_PERF_SEP),
        pick2("Ik ___ vanochtend om zes uur opgestaan.", ["ben", "heb"], "ben",
              "opstaan تغییر حالت/حرکت است → zijn.", concept=C_PERF_SEP),
        fix("Ik heb hem geopbeld.", "Ik heb hem opgebeld.",
            "ge بین پیشوند و فعل می‌نشیند.", concept=C_PERF_SEP),
        order("Ik ben vanochtend vroeg opgestaan.",
              why="فعل کمکی جای دوم، اسم مفعول کامل آخر.", concept=C_PERF_SEP),
        fa2nl("«دیروز بهش زنگ زدم.»", "Ik heb hem gisteren opgebeld.",
              "opbellen → opgebeld، با hebben.", concept=C_PERF_SEP),
        dialogue("— Hoe laat ben je vanochtend ___?", "— Om zes uur.",
                 ["opgestaan", "gestaan op", "geopstaan"], "opgestaan",
                 "شکل درست اسم مفعول: opgestaan.", concept=C_PERF_SEP),
    ])

lesson(
    "a2-l05", "a2-verleden", "A2",
    "Ik werkte, ik woonde", "ماضی ساده‌ی باقاعده",
    [C_PAST_REG],
    discover(
        ["werken → ik werkte, wij werkten", "wonen → ik woonde, wij woonden"],
        "چرا یکی -te گرفت و دیگری -de؟ همان قاعده‌ی ماضی نقلی را به یاد بیاور.",
        "دقیقاً همان 't kofschip: اگر ریشه به t، k، f، s، ch یا p ختم شود → te؛ وگرنه → de."),
    rule("stam + te(n) / de(n)",
         "همان قاعده‌ای که برای اسم مفعول یاد گرفتی. جمع فقط یک n اضافه می‌کند.",
         "simple past: stem + te/de"),
    pattern([("ik/jij/hij", "subject"), ("werkte", "verb"), ("|", "sep"),
             ("wij/jullie/zij", "subject"), ("werkten", "verb")],
            "برخلاف زمان حال، در ماضی ساده مفرد و جمع فقط یک n فرق دارند."),
    [
        ex("Ik werkte toen bij een school.", "آن موقع در یک مدرسه کار می‌کردم."),
        ex("We woonden vroeger in Iran.", "قبلاً در ایران زندگی می‌کردیم."),
        ex("Hij luisterde naar de radio.", "به رادیو گوش می‌داد."),
        ex("Zij studeerde in Delft.", "در دلفت درس می‌خواند."),
        ex("Het regende de hele dag.", "تمام روز باران می‌بارید."),
    ],
    [
        wrong("Ik werkde bij een school.", "Ik werkte bij een school.",
              "werk به k ختم می‌شود، پس te می‌گیرد."),
        wrong("Wij woonde in Iran.", "Wij woonden in Iran.",
              "در جمع یک n اضافه می‌شود."),
    ],
    "برای تعریف کردن گذشته‌ی طولانی و توصیف: «قبلاً کجا زندگی می‌کردی؟»، «آن موقع چه کار می‌کردی؟» در نوشتار خیلی بیشتر از گفتار دیده می‌شود.",
    [
        conjugate("ik (werken, verleden tijd) → ik ___", "werkte",
                  "ریشه werk + te.", concept=C_PAST_REG),
        conjugate("wij (wonen, verleden tijd) → wij ___", "woonden",
                  "ریشه woon + den (جمع).", concept=C_PAST_REG),
        mc("Hij ___ vroeger in Rotterdam. (wonen)", ["woonde", "woonte", "wonde"], "woonde",
           "woon به n ختم می‌شود → de.", concept=C_PAST_REG),
        mc("Ik ___ naar de radio. (luisteren)", ["luisterde", "luisterte", "luister"],
           "luisterde", "luister به r ختم می‌شود → de.", concept=C_PAST_REG),
        blank("Wij ___ toen in Delft. (studeren)", "studeerden",
              "ریشه studeer + den.", concept=C_PAST_REG),
        fix("Ik werkde daar drie jaar.", "Ik werkte daar drie jaar.",
            "بعد از k پسوند te می‌آید.", concept=C_PAST_REG),
        transform("Ik woon in Iran. → (ماضی ساده)", "Ik woonde in Iran.",
                  "ریشه + de.", concept=C_PAST_REG),
        fa2nl("«قبلاً در ایران زندگی می‌کردیم.»", "We woonden vroeger in Iran.", 
              "جمع → woonden.", alt=["Wij woonden vroeger in Iran."], concept=C_PAST_REG),
    ])

lesson(
    "a2-l06", "a2-verleden", "A2",
    "Was, had, ging, kwam", "ماضی ساده‌ی بی‌قاعده",
    [C_PAST_IRR],
    discover(
        ["zijn → ik was, wij waren", "hebben → ik had, wij hadden",
         "gaan → ik ging", "komen → ik kwam", "zeggen → ik zei"],
        "این‌ها te/de می‌گیرند؟",
        "نه. کلاً شکلشان عوض می‌شود. ولی خبر خوب: پرکاربردترین‌ها فقط همین چند تا هستند."),
    rule("was/waren · had/hadden · ging · kwam · zei · dacht",
         "این‌ها را باید حفظ کرد، ولی همین شش تا بیشترِ کاربرد روزمره را پوشش می‌دهند.",
         "was / had / went / came / said"),
    pattern([("ik was", "sg"), ("→", "arrow"), ("wij waren", "pl"), ("|", "sep"),
             ("ik had", "sg"), ("→", "arrow"), ("wij hadden", "pl")],
            "برای zijn و hebben حتی جمع هم بی‌قاعده است."),
    [
        ex("Ik was gisteren ziek.", "دیروز مریض بودم."),
        ex("We waren op vakantie.", "تعطیلات بودیم."),
        ex("Ik had geen tijd.", "وقت نداشتم."),
        ex("Hij ging naar huis.", "رفت خانه."),
        ex("Zij kwam te laat.", "دیر آمد."),
        ex("Hij zei dat het goed was.", "گفت که خوب است."),
    ],
    [
        wrong("Ik wasde ziek.", "Ik was ziek.",
              "zijn کاملاً بی‌قاعده است: was/waren."),
        wrong("Wij was op vakantie.", "Wij waren op vakantie.",
              "در جمع شکل waren می‌آید."),
    ],
    "was، had، ging و kwam را در هر داستان، هر خبر و هر تعریف کردنی می‌شنوی. حتی اگر بقیه‌ی ماضی ساده را کم به کار ببری، این‌ها ضروری‌اند.",
    [
        conjugate("ik (zijn, verleden tijd) → ik ___", "was",
                  "zijn → was.", concept=C_PAST_IRR),
        conjugate("wij (zijn, verleden tijd) → wij ___", "waren",
                  "جمع → waren.", concept=C_PAST_IRR),
        conjugate("ik (hebben, verleden tijd) → ik ___", "had",
                  "hebben → had.", concept=C_PAST_IRR),
        mc("Hij ___ gisteren naar Rotterdam. (gaan)", ["ging", "gingde", "gaat"], "ging",
           "gaan → ging.", concept=C_PAST_IRR),
        mc("Zij ___ te laat. (komen)", ["kwam", "kwamde", "komde"], "kwam",
           "komen → kwam.", concept=C_PAST_IRR),
        blank("Ik ___ geen tijd. (hebben, verleden tijd)", "had",
              "hebben → had.", concept=C_PAST_IRR),
        fix("Wij was op vakantie in Spanje.", "Wij waren op vakantie in Spanje.",
            "جمع zijn در گذشته می‌شود waren.", concept=C_PAST_IRR),
        fa2nl("«دیروز مریض بودم.»", "Ik was gisteren ziek.",
              "zijn در گذشته → was.", concept=C_PAST_IRR),
        order("Wij waren vorige week op vakantie.",
              why="فعل جای دوم، بقیه بعدش.", concept=C_PAST_IRR),
    ])

lesson(
    "a2-l07", "a2-verleden", "A2",
    "Perfectum of imperfectum?", "کدام گذشته را به کار ببرم؟",
    [C_PERF_VS_PAST],
    discover(
        ["— Wat heb je dit weekend gedaan?  — Ik ben naar mijn zus geweest.",
         "Vroeger woonden we in Iran. Mijn vader werkte bij een bank."],
        "در گفتگو کدام زمان به کار رفته و در روایت کدام؟",
        "در گفتگوی روزمره ماضی نقلی؛ در توصیف و روایتِ گذشته ماضی ساده. البته was و had همیشه ماضی ساده‌اند."),
    rule("gesprek → perfectum · verhaal en beschrijving → imperfectum",
         "ولی zijn، hebben و فعل‌های وجهی تقریباً همیشه به شکل ماضی ساده می‌آیند: was، had، moest، kon.",
         "spoken past vs. narrative past"),
    pattern([("Wat heb je gedaan?", "perfect"), ("→", "arrow"), ("Ik ben … geweest", "perfect"),
             ("|", "sep"), ("Vroeger woonde ik …", "past")],
            "قاعده‌ی عملی: اگر می‌شود گفت «دیروز/آخر هفته…»، ماضی نقلی."),
    [
        ex("Wat heb je gisteren gedaan?", "دیروز چه کار کردی؟"),
        ex("Ik heb een film gekeken.", "یک فیلم دیدم."),
        ex("Vroeger woonde ik in Teheran.", "قبلاً در تهران زندگی می‌کردم."),
        ex("Toen ik klein was, speelde ik veel buiten.", "وقتی بچه بودم، زیاد بیرون بازی می‌کردم."),
        ex("Ik kon gisteren niet komen.", "دیروز نتوانستم بیایم.", "فعل وجهی → ماضی ساده"),
    ],
    [
        wrong("Toen ik klein ben geweest…", "Toen ik klein was…",
              "با toen و برای توصیف گذشته ماضی ساده می‌آید."),
        wrong("Ik heb gisteren niet kunnen komen. (in spreektaal minder gebruikelijk)",
              "Ik kon gisteren niet komen.",
              "با فعل‌های وجهی، هلندی‌ها تقریباً همیشه ماضی ساده به کار می‌برند."),
    ],
    "این انتخاب طبیعی بودن هلندی‌ات را تعیین می‌کند. در مصاحبه‌ی کاری، وقتی از تجربه‌ات می‌پرسند، ترکیب هر دو لازم است: «Ik heb drie jaar gewerkt… Toen was ik verantwoordelijk voor…»",
    [
        pick2("— Wat ___ je dit weekend gedaan?", ["heb", "deed"], "heb",
              "در گفتگوی روزمره ماضی نقلی طبیعی‌تر است.", concept=C_PERF_VS_PAST),
        pick2("Toen ik klein ___, speelde ik veel buiten.", ["was", "ben geweest"], "was",
              "با toen همیشه ماضی ساده.", concept=C_PERF_VS_PAST),
        pick2("Ik ___ gisteren niet komen.", ["kon", "heb gekund"], "kon",
              "فعل‌های وجهی در گذشته معمولاً ماضی ساده می‌گیرند.", concept=C_PERF_VS_PAST),
        mc("Vroeger ___ wij in Iran.", ["woonden", "hebben gewoond", "wonen"], "woonden",
           "«vroeger» یعنی توصیف گذشته → ماضی ساده.", concept=C_PERF_VS_PAST),
        mc("— Ben je al bij de dokter geweest?  — Ja, ik ___ er gisteren.",
           ["was", "ben geweest", "is geweest"], "was",
           "بعد از اینکه موضوع مطرح شد، ماضی ساده طبیعی است.", concept=C_PERF_VS_PAST),
        fix("Toen ik jong ben geweest, heb ik veel gesport.",
            "Toen ik jong was, sportte ik veel.",
            "با toen و برای توصیف عادت‌های گذشته ماضی ساده می‌آید.", concept=C_PERF_VS_PAST),
        fa2nl("«آخر هفته چه کار کردی؟»", "Wat heb je dit weekend gedaan?",
              "گفتگوی روزمره → ماضی نقلی.", concept=C_PERF_VS_PAST),
        dialogue("— Wat heb je gisteren gedaan?",
                 "— Ik ___ naar mijn zus geweest.", ["ben", "heb", "was"], "ben",
                 "zijn → geweest، با فعل کمکی zijn.", concept=C_PERF_VS_PAST),
    ])

lesson(
    "a2-l08", "a2-bijzin", "A2",
    "En, maar, want, of, dus", "حروف ربط هم‌پایه",
    [C_COORD],
    discover(
        ["Ik ben moe, want ik heb hard gewerkt.",
         "Ik ben moe, omdat ik hard heb gewerkt."],
        "در جمله‌ی دوم فعل کجا رفت؟",
        "بعد از omdat فعل آخر می‌رود، ولی بعد از want ترتیب عادی می‌ماند. این تفاوت کلیدی است."),
    rule("en · maar · want · of · dus → gewone volgorde",
         "این پنج حرف ربط ترتیب جمله را دست نمی‌زنند: بعدشان دوباره فاعل + فعل می‌آید.",
         "and / but / because / or / so"),
    pattern([("Ik ben moe", "clause"), (",", "comma"), ("want", "conj"),
             ("ik", "subject"), ("heb", "verb"), ("hard gewerkt", "rest")],
            "پنج تا هستند و بس. هر حرف ربط دیگری، فعل را به آخر می‌فرستد."),
    [
        ex("Ik werk en zij studeert.", "من کار می‌کنم و او درس می‌خواند."),
        ex("Ik wil komen, maar ik heb geen tijd.", "می‌خواهم بیایم، ولی وقت ندارم."),
        ex("Ik ga naar bed, want ik ben moe.", "می‌روم بخوابم، چون خسته‌ام."),
        ex("Kom je vandaag of morgen?", "امروز می‌آیی یا فردا؟"),
        ex("Het regent, dus ik neem de bus.", "باران می‌بارد، پس با اتوبوس می‌روم."),
    ],
    [
        wrong("Ik ben moe, want ik hard gewerkt heb.", "Ik ben moe, want ik heb hard gewerkt.",
              "بعد از want ترتیب عادی می‌ماند؛ فعل به آخر نمی‌رود."),
        wrong("Het regent, dus neem ik de bus. (ook goed, maar let op)",
              "Het regent, dus ik neem de bus.",
              "با dus هر دو شنیده می‌شود، ولی ساده‌ترین و مطمئن‌ترین شکل ترتیب عادی است."),
    ],
    "با همین پنج کلمه می‌توانی جمله‌هایت را به هم وصل کنی بدون اینکه ترتیب کلمات را عوض کنی — ساده‌ترین راه برای طولانی‌تر حرف زدن.",
    [
        mc("Ik ga naar bed, ___ ik ben moe.", ["want", "omdat", "dat"], "want",
           "بعد از want ترتیب عادی می‌ماند و اینجا جمله ترتیب عادی دارد.", concept=C_COORD),
        pickorder("کدام درست است؟",
                  ["Ik kom niet, want ik ben ziek.", "Ik kom niet, want ik ziek ben."],
                  "Ik kom niet, want ik ben ziek.",
                  "want ترتیب را عوض نمی‌کند.", concept=C_COORD),
        mc("Ik wil komen, ___ ik heb geen tijd.", ["maar", "omdat", "dat"], "maar",
           "تضاد بین دو جمله → maar.", concept=C_COORD),
        order("Het regent dus ik neem de bus.",
              why="بعد از dus جمله‌ی کامل با ترتیب عادی می‌آید.", concept=C_COORD),
        blank("Ik werk ___ zij studeert.", "en",
              "دو جمله‌ی هم‌ارز → en.", concept=C_COORD),
        fix("Ik blijf thuis, want het slecht weer is.",
            "Ik blijf thuis, want het weer slecht is.",
            "خودِ ترتیب بعد از want عادی است: het weer is slecht. شکل درست: «want het weer is slecht».",
            concept=C_COORD),
        fa2nl("«خسته‌ام، چون سخت کار کردم.» (با want)",
              "Ik ben moe, want ik heb hard gewerkt.",
              "بعد از want: فاعل + فعل + بقیه.", concept=C_COORD),
        pick2("Kom je vandaag ___ morgen?", ["of", "en"], "of",
              "انتخاب بین دو گزینه → of.", concept=C_COORD),
    ])

lesson(
    "a2-l09", "a2-bijzin", "A2",
    "Omdat, dat, als: werkwoord achteraan", "جمله‌واره: فعل در انتها",
    [C_SUB],
    discover(
        ["Ik kom niet. Ik ben ziek.",
         "Ik kom niet, omdat ik ziek ben.",
         "Ik denk dat hij morgen komt."],
        "بعد از omdat و dat، فعل کجا ایستاده؟",
        "آخرِ آخر. هر جمله‌واره‌ای که با این حرف‌های ربط شروع شود، فعلش می‌رود ته جمله."),
    rule("omdat / dat / als / terwijl / hoewel → werkwoord helemaal achteraan",
         "این مهم‌ترین ساختار سطح A2 است. بعد از این حرف‌های ربط، فعلِ صرف‌شده آخرین کلمه می‌شود.",
         "subordinate clause: verb goes last"),
    pattern([("omdat", "conj"), ("ik", "subject"), ("gisteren", "time"),
             ("hard", "manner"), ("gewerkt heb", "verb-end")],
            "اگر دو فعل باشد، هر دو با هم آخر می‌روند: … gewerkt heb / … heb gewerkt (هر دو درست‌اند)."),
    [
        ex("Ik kom niet, omdat ik ziek ben.", "نمی‌آیم، چون مریضم."),
        ex("Ik denk dat hij gelijk heeft.", "فکر می‌کنم حق با اوست."),
        ex("Als het regent, blijf ik thuis.", "اگر باران ببارد، خانه می‌مانم."),
        ex("Ik weet dat je het druk hebt.", "می‌دانم سرت شلوغ است."),
        ex("Hij belde terwijl ik aan het koken was.", "وقتی داشتم آشپزی می‌کردم زنگ زد."),
    ],
    [
        wrong("Ik kom niet, omdat ik ben ziek.", "Ik kom niet, omdat ik ziek ben.",
              "بعد از omdat فعل باید آخر برود."),
        wrong("Ik denk dat hij komt morgen.", "Ik denk dat hij morgen komt.",
              "فعل آخرین کلمه‌ی جمله‌واره است، پس بعد از «morgen» می‌آید."),
    ],
    "به محض اینکه بخواهی دلیل بیاوری، نظر بدهی یا شرط بگذاری، به جمله‌واره نیاز داری. در مصاحبه‌ی کاری جمله‌هایی مثل «Ik denk dat…» و «omdat ik…» مدام لازم می‌شوند.",
    [
        pickorder("کدام درست است؟",
                  ["Ik kom niet, omdat ik ziek ben.", "Ik kom niet, omdat ik ben ziek."],
                  "Ik kom niet, omdat ik ziek ben.",
                  "بعد از omdat فعل آخر می‌رود.", concept=C_SUB),
        pickorder("کدام درست است؟",
                  ["Ik denk dat hij morgen komt.", "Ik denk dat hij komt morgen."],
                  "Ik denk dat hij morgen komt.",
                  "فعل آخرین کلمه‌ی جمله‌واره است.", concept=C_SUB),
        subclause("Ik weet dat je het druk hebt.",
                  why="بعد از dat: فاعل + بقیه + فعل.", concept=C_SUB),
        subclause("Hij zegt dat hij morgen komt.",
                  why="فعل komt آخرین کلمه است.", concept=C_SUB),
        transform("Ik kom niet. Ik ben ziek. → (met «omdat»)",
                  "Ik kom niet, omdat ik ziek ben.",
                  "omdat فعل را به آخر می‌فرستد.", concept=C_SUB),
        fix("Ik denk dat het is een goed idee.", "Ik denk dat het een goed idee is.",
            "بعد از dat فعل is آخر می‌رود.", concept=C_SUB),
        fa2nl("«فکر می‌کنم حق با توست.»", "Ik denk dat je gelijk hebt.",
              "بعد از dat: je gelijk hebt (فعل آخر).", concept=C_SUB),
        blank("Ik blijf thuis omdat het ___. (regenen)", "regent",
              "فعل جمله‌واره آخر می‌آید: … omdat het regent.", concept=C_SUB),
        dialogue("— Waarom kom je niet?",
                 "— Omdat ik geen tijd ___.", ["heb", "heb niet", "hebt"], "heb",
                 "بعد از omdat فعل آخر می‌رود: omdat ik geen tijd heb.", concept=C_SUB),
    ])

lesson(
    "a2-l10", "a2-bijzin", "A2",
    "Als de bijzin eerst komt", "وقتی جمله‌واره اول می‌آید",
    [C_SUB_ORDER, C_SUB],
    discover(
        ["Ik blijf thuis als het regent.",
         "Als het regent, blijf ik thuis."],
        "در جمله‌ی دوم چرا blijf قبل از ik آمده؟",
        "چون کل جمله‌واره «جای اول» را گرفته است. پس فعلِ جمله‌ی اصلی باید بلافاصله بعدش بیاید — همان قانون «فعل جای دوم»."),
    rule("bijzin op plaats 1 → daarna meteen het werkwoord",
         "جمله‌واره یک بخش کامل حساب می‌شود. بعد از کاما، اول فعل می‌آید و بعد فاعل.",
         "clause first, then verb, then subject"),
    pattern([("Als het regent", "clause-1"), (",", "comma"), ("blijf", "verb"),
             ("ik", "subject"), ("thuis", "rest")],
            "به این حالت می‌گویند «دو فعل که به هم می‌رسند»: … regent, blijf …"),
    [
        ex("Als het regent, blijf ik thuis.", "اگر باران ببارد، خانه می‌مانم."),
        ex("Omdat ik ziek was, ben ik niet gekomen.", "چون مریض بودم، نیامدم."),
        ex("Toen ik klein was, woonden we in Iran.", "وقتی بچه بودم، در ایران زندگی می‌کردیم."),
        ex("Als je tijd hebt, kunnen we koffie drinken.", "اگر وقت داشته باشی، می‌توانیم قهوه بخوریم."),
    ],
    [
        wrong("Als het regent, ik blijf thuis.", "Als het regent, blijf ik thuis.",
              "جمله‌واره جای اول را گرفته، پس فعل جمله‌ی اصلی باید بلافاصله بعد از کاما بیاید."),
        wrong("Omdat ik ziek was, ik ben niet gekomen.",
              "Omdat ik ziek was, ben ik niet gekomen.",
              "همان قانون: بعد از کاما اول فعل، بعد فاعل."),
    ],
    "هلندی‌ها خیلی دوست دارند جمله را با «Als…» یا «Toen…» شروع کنند. اگر این را درست بگویی، سطحت بلافاصله بالاتر شنیده می‌شود.",
    [
        pickorder("کدام درست است؟",
                  ["Als het regent, blijf ik thuis.", "Als het regent, ik blijf thuis."],
                  "Als het regent, blijf ik thuis.",
                  "بعد از جمله‌واره‌ی اول، فعل می‌آید.", concept=C_SUB_ORDER),
        pickorder("کدام درست است؟",
                  ["Omdat ik moe ben, ga ik naar bed.", "Omdat ik moe ben, ik ga naar bed."],
                  "Omdat ik moe ben, ga ik naar bed.",
                  "کل جمله‌واره جای اول است → فعل جای دوم.", concept=C_SUB_ORDER),
        order("Als je tijd hebt, kunnen we koffie drinken.",
              why="جمله‌واره اول، بعد فعل kunnen، بعد فاعل we.", concept=C_SUB_ORDER),
        transform("Ik blijf thuis als het regent. → (جمله را با «Als» شروع کن)",
                  "Als het regent, blijf ik thuis.",
                  "جمله‌واره جلو می‌آید و فعل جمله‌ی اصلی بلافاصله بعد از کاما.",
                  concept=C_SUB_ORDER),
        transform("Ik ben niet gekomen omdat ik ziek was. → (با «Omdat» شروع کن)",
                  "Omdat ik ziek was, ben ik niet gekomen.",
                  "همان قاعده، این بار با ماضی نقلی.", concept=C_SUB_ORDER),
        fix("Toen ik klein was, wij woonden in Iran.",
            "Toen ik klein was, woonden wij in Iran.",
            "بعد از جمله‌واره، فعل قبل از فاعل می‌آید.", concept=C_SUB_ORDER),
        fa2nl("«اگر وقت داشته باشی، می‌توانیم قهوه بخوریم.»",
              "Als je tijd hebt, kunnen we koffie drinken.",
              "جمله‌واره + کاما + فعل + فاعل.", concept=C_SUB_ORDER),
        scenario("Je wilt zeggen dat je morgen niet komt als je ziek blijft.",
                 "Wat zeg je?",
                 ["Als ik ziek blijf, kom ik morgen niet.",
                  "Als ik ziek blijf, ik kom morgen niet.",
                  "Als blijf ik ziek, kom ik morgen niet."],
                 "Als ik ziek blijf, kom ik morgen niet.",
                 "در جمله‌واره فعل آخر (blijf)، و بعد از کاما فعل جمله‌ی اصلی اول (kom).",
                 concept=C_SUB_ORDER),
    ])

lesson(
    "a2-l11", "a2-bijzin", "A2",
    "Weet je of hij komt?", "سؤال غیرمستقیم",
    [C_INDIRECT_Q],
    discover(
        ["Komt hij morgen?  →  Weet je of hij morgen komt?",
         "Waar woont zij?  →  Ik weet niet waar zij woont."],
        "وقتی سؤال داخل جمله می‌رود، چه اتفاقی برای فعل می‌افتد؟",
        "به آخر می‌رود، چون تبدیل به جمله‌واره شده. سؤال بله/خیر هم of می‌گیرد."),
    rule("ja/nee-vraag → of · vraagwoord blijft · werkwoord achteraan",
         "«Komt hij?» می‌شود «…of hij komt». «Waar woont zij?» می‌شود «…waar zij woont».",
         "indirect questions use 'of' and verb-final order"),
    pattern([("Weet je", "main"), ("of", "conj"), ("hij", "subject"),
             ("morgen", "time"), ("komt", "verb-end")],
            "این ساختار مؤدبانه‌تر از سؤال مستقیم است و در اداره‌ها زیاد به کار می‌رود."),
    [
        ex("Weet je of de winkel open is?", "می‌دانی مغازه باز است؟"),
        ex("Ik weet niet waar hij woont.", "نمی‌دانم کجا زندگی می‌کند."),
        ex("Kunt u mij zeggen hoe laat de trein vertrekt?", "می‌شود بگویید قطار ساعت چند حرکت می‌کند؟"),
        ex("Ik vraag me af of dat klopt.", "برایم سؤال است که آیا درست است."),
        ex("Weet jij wanneer de les begint?", "می‌دانی کلاس کِی شروع می‌شود؟"),
    ],
    [
        wrong("Weet je of komt hij morgen?", "Weet je of hij morgen komt?",
              "بعد از of ترتیب جمله‌واره است: فاعل … فعل آخر."),
        wrong("Ik weet niet waar woont hij.", "Ik weet niet waar hij woont.",
              "در سؤال غیرمستقیم فعل به آخر می‌رود، حتی با کلمه‌ی پرسشی."),
    ],
    "در اداره، مغازه و محل کار: «Kunt u mij zeggen of…?» و «Weet u waar…?» مؤدبانه‌ترین راه پرسیدن‌اند. در مصاحبه هم بسیار طبیعی است.",
    [
        mc("Weet je ___ de winkel open is?", ["of", "dat", "als"], "of",
           "سؤال بله/خیر داخل جمله → of.", concept=C_INDIRECT_Q),
        pickorder("کدام درست است؟",
                  ["Weet je of hij morgen komt?", "Weet je of komt hij morgen?"],
                  "Weet je of hij morgen komt?",
                  "بعد از of، فعل آخر می‌رود.", concept=C_INDIRECT_Q),
        pickorder("کدام درست است؟",
                  ["Ik weet niet waar zij woont.", "Ik weet niet waar woont zij."],
                  "Ik weet niet waar zij woont.",
                  "کلمه‌ی پرسشی می‌ماند، ولی فعل آخر می‌رود.", concept=C_INDIRECT_Q),
        transform("Komt hij morgen? → (met «Weet je …»)", "Weet je of hij morgen komt?",
                  "of + فاعل + بقیه + فعل.", concept=C_INDIRECT_Q),
        transform("Hoe laat vertrekt de trein? → (met «Weet u …»)",
                  "Weet u hoe laat de trein vertrekt?",
                  "کلمه‌ی پرسشی می‌ماند و فعل آخر می‌رود.", concept=C_INDIRECT_Q),
        fix("Ik vraag me af of klopt dat.", "Ik vraag me af of dat klopt.",
            "بعد از of ترتیب جمله‌واره است.", concept=C_INDIRECT_Q),
        fa2nl("«می‌دانی مغازه باز است؟»", "Weet je of de winkel open is?",
              "of + جمله‌واره با فعل آخر.", concept=C_INDIRECT_Q),
        scenario("Je wilt beleefd vragen waar het station is.",
                 "Wat zeg je?",
                 ["Kunt u mij zeggen waar het station is?",
                  "Kunt u mij zeggen waar is het station?",
                  "Weet u waar is het station?"],
                 "Kunt u mij zeggen waar het station is?",
                 "در سؤال غیرمستقیم فعل آخر می‌آید — و این مؤدبانه‌ترین شکل پرسیدن است.",
                 concept=C_INDIRECT_Q),
    ])

# ----------------------------------------------------------------- modules

module("a2-perfectum", "A2", "Het perfectum", "ماضی نقلی",
       "درباره‌ی گذشته حرف بزنی: ساخت اسم مفعول، انتخاب hebben یا zijn، و افعال جداشدنی.",
       ["a2-l01", "a2-l02", "a2-l03", "a2-l04"], icon="clock")

module("a2-verleden", "A2", "De verleden tijd", "ماضی ساده",
       "گذشته را روایت کنی و بدانی کِی ماضی ساده و کِی ماضی نقلی طبیعی است.",
       ["a2-l05", "a2-l06", "a2-l07"], icon="book")

module("a2-bijzin", "A2", "Bijzinnen", "جمله‌واره‌ها",
       "جمله‌هایت را با omdat، dat و als طولانی کنی — و فعل را در جای درست بگذاری.",
       ["a2-l08", "a2-l09", "a2-l10", "a2-l11"], icon="list")
