"""B1, deel 2 — werkwoordgroepen, conditioneel en natuurlijk klinkend Nederlands."""

from _kit import (concept, lesson, module, ex, wrong, pattern, discover, rule,
                  mc, dehet, nietgeen, pickorder, pick2, dialogue, scenario,
                  blank, conjugate, transform, fa2nl, fix, type_all,
                  order, question, subclause)

# ---------------------------------------------------------------- concepts

C_VERB_CLUSTER = concept(
    "verb-cluster", "Meerdere werkwoorden achteraan", "خوشه‌ی فعلی در انتها", "B1",
    keywords=["werkwoordgroep", "hebben kunnen", "moeten doen", "volgorde werkwoorden"],
    summary_fa="وقتی چند فعل ته جمله جمع می‌شوند، فعل کمکی معمولاً اول می‌آید.")

C_LATEN = concept(
    "verb-laten", "Laten, horen, zien + infinitief", "laten و افعال ادراکی", "B1",
    keywords=["laten", "horen", "zien", "laten repareren", "laten weten"],
    summary_fa="laten یعنی «کاری را دادن به کسی» یا «گذاشتن»: Ik laat mijn auto repareren.")

C_HOEVEN = concept(
    "verb-hoeven", "Hoeven: niet moeten", "hoeven: لازم نبودن", "B1",
    keywords=["hoeven", "hoeft niet", "moeten hoeven", "niet nodig"],
    summary_fa="نفیِ moeten می‌شود hoeven niet te — «لازم نیست».")

C_AAN_HET = concept(
    "aan-het", "Aan het + infinitief", "aan het + مصدر (در حال انجام)", "B1",
    keywords=["aan het", "bezig", "aan het werken", "در حال"],
    summary_fa="zijn + aan het + مصدر = «دارم … می‌کنم» (همین الان در جریان).")

C_ZOU = concept(
    "conditional-zou", "Zou en zouden", "zou: شرطی و مؤدبانه", "B1",
    keywords=["zou", "zouden", "beleefd", "zou graag", "conditioneel", "شرطی"],
    summary_fa="zou + مصدر: هم برای ادب («Ik zou graag…») و هم برای فرض.")

C_ALS_DAN = concept(
    "conditional-als", "Als … dan", "جمله‌ی شرطی", "B1",
    keywords=["als", "dan", "voorwaarde", "als ik jou was", "شرط"],
    summary_fa="Als + جمله‌واره، dan + جمله‌ی اصلی. برای فرض غیرواقعی: als ik … zou.")

C_PARTICLE = concept(
    "modal-particles", "Kleine woordjes: even, maar, toch, wel, eens", "کلمات کوچک لحن‌ساز", "B1",
    keywords=["even", "maar", "toch", "wel", "eens", "hoor", "partikel", "لحن"],
    summary_fa="این کلمه‌ها معنی جمله را عوض نمی‌کنند، لحن را عوض می‌کنند.")

C_REPORTED = concept(
    "reported-speech", "Verslag doen: hij zei dat …", "نقل قول غیرمستقیم", "B1",
    keywords=["hij zei dat", "indirecte rede", "volgens", "reported speech", "نقل قول"],
    summary_fa="با dat جمله‌واره می‌سازیم و فعلش آخر می‌رود؛ ضمیرها هم عوض می‌شوند.")

C_WORK_PHRASES = concept(
    "formal-work-phrases", "Vaste constructies op het werk", "عبارت‌های ثابت محیط کار", "B1",
    keywords=["ik zou graag", "het lijkt me", "ik ben benieuwd", "sollicitatie", "مصاحبه"],
    summary_fa="عبارت‌های آماده‌ای که در مصاحبه و ایمیل کاری مدام لازم می‌شوند.")

# ----------------------------------------------------------------- lessons

lesson(
    "b1-l07", "b1-werkwoordgroep", "B1",
    "Ik had het kunnen doen", "چند فعل در انتهای جمله",
    [C_VERB_CLUSTER],
    discover(
        ["Ik heb het gedaan.", "Ik heb het kunnen doen.",
         "Ik had het moeten vragen.", "Hij zegt dat hij niet heeft kunnen komen."],
        "وقتی سه فعل ته جمله جمع می‌شوند، کدام اول می‌آید؟",
        "فعل کمکی (heb/had) اول، بعد فعل وجهی، بعد فعل اصلی. و به جای «gekund» مصدر kunnen می‌آید."),
    rule("hulpwerkwoord → modaal → hoofdwerkwoord (allemaal infinitief)",
         "به این پدیده می‌گویند «مصدر جایگزین»: به جای اسم مفعولِ فعل وجهی، مصدر آن می‌آید.",
         "I could have done it"),
    pattern([("Ik", "subject"), ("had", "aux"), ("het", "object"),
             ("moeten", "modal-inf"), ("vragen", "main-inf")],
            "هیچ‌وقت «gemoeten» یا «gekund» نمی‌گوییم وقتی فعل دومی در کار است."),
    [
        ex("Ik had het eerder moeten zeggen.", "باید زودتر می‌گفتم."),
        ex("Hij heeft niet kunnen komen.", "نتوانست بیاید."),
        ex("We hadden het anders moeten doen.", "باید جور دیگری انجامش می‌دادیم."),
        ex("Ik zou het graag hebben willen zien.", "دلم می‌خواست می‌دیدمش."),
        ex("Sorry dat ik niet heb kunnen bellen.", "ببخشید که نتوانستم زنگ بزنم."),
    ],
    [
        wrong("Ik heb het gekund doen.", "Ik heb het kunnen doen.",
              "وقتی بعد از فعل وجهی فعل دیگری بیاید، مصدر جایگزینِ اسم مفعول می‌شود."),
        wrong("Ik had het moeten gezegd.", "Ik had het moeten zeggen.",
              "فعل اصلی هم مصدر می‌ماند: moeten zeggen."),
    ],
    "برای عذرخواهی و توضیح دادن — «Sorry, ik heb niet kunnen komen» و «Ik had het eerder moeten laten weten» در محیط کار مدام لازم می‌شوند.",
    [
        mc("Ik heb hem niet ___ bereiken.", ["kunnen", "gekund", "kon"], "kunnen",
           "با فعل دوم، مصدر جایگزین اسم مفعول می‌شود.", concept=C_VERB_CLUSTER),
        mc("Ik had het eerder ___ zeggen.", ["moeten", "gemoeten", "moest"], "moeten",
           "همان قاعده: moeten، نه gemoeten.", concept=C_VERB_CLUSTER),
        pickorder("کدام درست است؟",
                  ["Ik heb niet kunnen komen.", "Ik heb niet komen kunnen.",
                   "Ik heb niet gekund komen."],
                  "Ik heb niet kunnen komen.",
                  "فعل کمکی، بعد فعل وجهی، بعد فعل اصلی.", concept=C_VERB_CLUSTER),
        order("Ik had het eerder moeten vragen.",
              why="had جای دوم، بعد moeten، بعد vragen.", concept=C_VERB_CLUSTER),
        fix("Sorry, ik heb niet gekund bellen.", "Sorry, ik heb niet kunnen bellen.",
            "kunnen به شکل مصدر می‌آید، نه gekund.", concept=C_VERB_CLUSTER),
        transform("Ik kon niet komen. → (ماضی نقلی)", "Ik heb niet kunnen komen.",
                  "heb + kunnen + komen.", concept=C_VERB_CLUSTER),
        fa2nl("«باید زودتر می‌گفتم.»", "Ik had het eerder moeten zeggen.",
              "had + moeten + zeggen.", concept=C_VERB_CLUSTER),
        subclause("Hij zegt dat hij niet heeft kunnen komen.",
                  why="در جمله‌واره کل خوشه‌ی فعلی آخر می‌رود.", concept=C_VERB_CLUSTER),
    ])

lesson(
    "b1-l08", "b1-werkwoordgroep", "B1",
    "Ik laat mijn auto repareren", "laten، horen، zien",
    [C_LATEN],
    discover(
        ["Ik repareer mijn auto.", "Ik laat mijn auto repareren.",
         "Ik hoor de kinderen spelen."],
        "در جمله‌ی دوم چه کسی ماشین را تعمیر می‌کند؟",
        "من نه — یکی دیگر. laten یعنی «کاری را به کسی سپردن». این ساختار در فارسی معادل مستقیم ندارد."),
    rule("laten + infinitief = iemand anders doet het",
         "laten همچنین یعنی «گذاشتن/اجازه دادن»: Laat maar. · Laat me weten.",
         "have something done"),
    pattern([("Ik", "subject"), ("laat", "laten"), ("mijn auto", "object"), ("repareren", "infinitive")],
            "horen، zien و voelen هم همین ساختار را می‌گیرند: Ik hoor hem zingen."),
    [
        ex("Ik laat mijn fiets repareren.", "دوچرخه‌ام را می‌دهم تعمیر کنند."),
        ex("Laat het me even weten.", "خبرش را بهم بده.", "عبارت بسیار پرکاربرد در کار"),
        ex("Ik hoor de buren praten.", "صدای حرف زدن همسایه‌ها را می‌شنوم."),
        ex("Laat maar, ik doe het zelf.", "ولش کن، خودم انجامش می‌دهم."),
        ex("Ze liet haar haar knippen.", "موهایش را کوتاه کرد (توسط آرایشگر)."),
    ],
    [
        wrong("Ik repareer mijn auto bij de garage.",
              "Ik laat mijn auto repareren bij de garage.",
              "اگر خودت تعمیر نمی‌کنی، laten لازم است — وگرنه یعنی خودت مکانیکی."),
        wrong("Laat mij weten het.", "Laat het me even weten.",
              "ترتیب: laat + مفعول + ضمیر + مصدر."),
    ],
    "«Ik laat het je weten» و «Laat maar weten» را در هر ایمیل کاری می‌بینی. و برای هر خدماتی (تعمیر، آرایشگاه، دکتر) لازمش داری.",
    [
        mc("Ik ___ mijn auto repareren.", ["laat", "repareer", "maak"], "laat",
           "کار را دیگری انجام می‌دهد → laten.", concept=C_LATEN),
        pickorder("کدام درست است؟",
                  ["Laat het me even weten.", "Laat mij weten het.", "Weet het me laten."],
                  "Laat het me even weten.",
                  "ترتیب ثابت: laat + het + me + weten.", concept=C_LATEN),
        blank("Ik ___ mijn haar knippen bij de kapper.", "laat",
              "آرایشگر کار را می‌کند → laten.", concept=C_LATEN),
        order("Ik hoor de kinderen buiten spelen.",
              why="horen + مفعول + مصدر در انتها.", concept=C_LATEN),
        transform("De garage repareert mijn auto. → (met «laten», vanuit «ik»)",
                  "Ik laat mijn auto repareren.",
                  "laten + مفعول + مصدر.", concept=C_LATEN),
        fix("Ik laat weten het je morgen.", "Ik laat het je morgen weten.",
            "مصدر weten آخر می‌رود و ضمیرها قبلش می‌آیند.", concept=C_LATEN),
        fa2nl("«خبرش را بهت می‌دهم.»", "Ik laat het je weten.",
              "عبارت ثابت: laten + het + je + weten.", concept=C_LATEN),
        scenario("Een collega vraagt of je morgen naar de vergadering komt, maar je weet het nog niet.",
                 "Wat zeg je?",
                 ["Ik laat het je morgen weten.", "Ik weet het je morgen laten.",
                  "Ik laat weten het morgen."],
                 "Ik laat het je morgen weten.",
                 "این طبیعی‌ترین جمله‌ی کاری برای «بعداً خبر می‌دهم» است.", concept=C_LATEN),
    ])

lesson(
    "b1-l09", "b1-werkwoordgroep", "B1",
    "Dat hoeft niet", "hoeven: لازم نیست",
    [C_HOEVEN],
    discover(
        ["Je moet komen.", "Je hoeft niet te komen.", "Dat hoeft niet."],
        "نفیِ moeten چه شد؟",
        "«moet niet» یعنی «نباید» (ممنوع). برای «لازم نیست» باید hoeven niet te گفت. این تفاوت مهم است."),
    rule("moeten niet = verboden · hoeven niet te = niet nodig",
         "hoeven تقریباً همیشه با niet یا geen می‌آید و te می‌خواهد.",
         "don't have to vs. must not"),
    pattern([("Je", "subject"), ("hoeft", "verb"), ("niet", "neg"),
             ("te komen", "te-inf")],
            "«Dat hoeft niet» به‌تنهایی هم یک جمله‌ی کامل و بسیار پرکاربرد است."),
    [
        ex("Je hoeft niet te betalen.", "لازم نیست پول بدهی."),
        ex("Dat hoeft niet, dank je.", "لازم نیست، ممنون."),
        ex("Ik hoef morgen niet te werken.", "فردا لازم نیست کار کنم."),
        ex("Je hoeft je geen zorgen te maken.", "لازم نیست نگران باشی."),
        ex("Je moet niet te laat komen.", "نباید دیر بیایی.", "این یعنی «ممنوع»، نه «لازم نیست»"),
    ],
    [
        wrong("Je moet niet komen. (bedoel je: het is niet nodig)",
              "Je hoeft niet te komen.",
              "«moet niet» یعنی «نیا!». اگر منظورت «مجبور نیستی» است، hoeven لازم است."),
        wrong("Je hoeft niet komen.", "Je hoeft niet te komen.",
              "hoeven همیشه te می‌خواهد."),
    ],
    "این تفاوت می‌تواند سوءتفاهم جدی بسازد: «Je moet niet komen» یعنی نیا. در محیط کار حتماً درست به کارش ببر.",
    [
        pick2("Je ___ niet te betalen, het is gratis.", ["hoeft", "moet"], "hoeft",
              "«لازم نیست» → hoeven niet te.", concept=C_HOEVEN),
        pick2("Je ___ niet te laat komen, dat mag niet.", ["moet", "hoeft"], "moet",
              "«نباید» (ممنوع) → moeten niet.", concept=C_HOEVEN),
        mc("Ik ___ morgen niet te werken.", ["hoef", "hoeft", "moet"], "hoef",
           "با ik شکل hoef.", concept=C_HOEVEN),
        blank("Je hoeft je geen zorgen ___ maken.", "te",
              "hoeven همیشه te می‌خواهد.", concept=C_HOEVEN),
        transform("Ik moet morgen werken. → (منفی: لازم نیست)",
                  "Ik hoef morgen niet te werken.",
                  "نفیِ «باید» می‌شود hoeven niet te.", concept=C_HOEVEN),
        fix("Je hoeft niet komen morgen.", "Je hoeft morgen niet te komen.",
            "te لازم است و زمان قبل از niet می‌آید.", concept=C_HOEVEN),
        fa2nl("«لازم نیست پول بدهی.»", "Je hoeft niet te betalen.",
              "hoeven + niet + te + مصدر.", concept=C_HOEVEN),
        dialogue("— Zal ik je helpen met dragen?", "— ___, het lukt wel.",
                 ["Dat hoeft niet", "Dat moet niet", "Dat kan niet"], "Dat hoeft niet",
                 "«Dat hoeft niet» یعنی «لازم نیست، ممنون» — رد کردن مؤدبانه.",
                 concept=C_HOEVEN),
    ])

lesson(
    "b1-l10", "b1-werkwoordgroep", "B1",
    "Ik ben aan het werken", "aan het + مصدر",
    [C_AAN_HET],
    discover(
        ["Ik werk bij een bank.", "Ik ben aan het werken.",
         "Ik ben bezig met het rapport."],
        "فرق دو جمله‌ی اول چیست؟",
        "اولی یعنی شغلم این است؛ دومی یعنی همین الان مشغولم. هلندی برای «در حال انجام» ساختار جدا دارد."),
    rule("zijn + aan het + infinitief",
         "برای کاری که همین حالا در جریان است. مثل «I am working» انگلیسی.",
         "to be …ing"),
    pattern([("Ik", "subject"), ("ben", "zijn"), ("aan het", "aan-het"), ("koken", "infinitive")],
            "«bezig zijn met + اسم» هم همین معنی را می‌دهد: Ik ben bezig met het rapport."),
    [
        ex("Ik ben aan het koken.", "دارم آشپزی می‌کنم."),
        ex("Wat ben je aan het doen?", "داری چه کار می‌کنی؟"),
        ex("Hij is aan het bellen.", "دارد تلفن حرف می‌زند."),
        ex("We zijn aan het wachten op de trein.", "منتظر قطاریم."),
        ex("Ik ben bezig met een nieuw project.", "روی یک پروژه‌ی جدید کار می‌کنم."),
    ],
    [
        wrong("Ik ben werkend.", "Ik ben aan het werken.",
              "هلندی برای «در حال انجام» شکل -end را به کار نمی‌برد؛ ساختارش aan het + مصدر است."),
        wrong("Ik ben aan het werk. (als je bedoelt: bezig)",
              "Ik ben aan het werken.",
              "«aan het werk» یعنی «سر کار»؛ برای «مشغول کار کردن» مصدر لازم است."),
    ],
    "برای گفتن اینکه الان مشغول چه کاری هستی — پشت تلفن، در پیام و سر کار. «Wat ben je aan het doen?» جمله‌ی روزمره است.",
    [
        mc("Wat ben je aan het ___?", ["doen", "doet", "gedaan"], "doen",
           "بعد از aan het مصدر می‌آید.", concept=C_AAN_HET),
        pickorder("کدام درست است؟",
                  ["Ik ben aan het koken.", "Ik ben kokend.", "Ik ben aan het kook."],
                  "Ik ben aan het koken.",
                  "zijn + aan het + مصدر.", concept=C_AAN_HET),
        blank("Hij is ___ het bellen.", "aan",
              "ساختار ثابت: aan het + مصدر.", concept=C_AAN_HET),
        order("Ik ben aan het werken.",
              why="zijn + aan het + مصدر.", concept=C_AAN_HET),
        transform("Ik kook. → (met «aan het»)", "Ik ben aan het koken.",
                  "zijn + aan het + مصدر.", concept=C_AAN_HET),
        fix("Ik ben werkend aan het rapport.", "Ik ben aan het werken aan het rapport.", 
            "شکل -end در هلندی برای این کار به کار نمی‌رود.", alt=["Ik ben bezig met het rapport."], concept=C_AAN_HET),
        fa2nl("«دارم آشپزی می‌کنم.»", "Ik ben aan het koken.",
              "zijn + aan het + مصدر.", concept=C_AAN_HET),
        dialogue("— Heb je even tijd?", "— Sorry, ik ben ___ een vergadering.",
                 ["in", "aan het", "bezig"], "in",
                 "«in een vergadering» یعنی داخل جلسه‌ام — با اسم از حرف اضافه استفاده می‌شود.",
                 concept=C_AAN_HET),
    ])

lesson(
    "b1-l11", "b1-conditioneel", "B1",
    "Ik zou graag …", "zou: ادب و فرض",
    [C_ZOU],
    discover(
        ["Ik wil een afspraak maken.", "Ik zou graag een afspraak willen maken.",
         "Als ik rijk was, zou ik een huis kopen."],
        "کدام مؤدبانه‌تر است و چرا؟",
        "دومی. zou جمله را نرم و غیرمستقیم می‌کند — دقیقاً کاری که «می‌خواستم…» در فارسی می‌کند."),
    rule("zou / zouden + infinitief",
         "دو کاربرد: مؤدبانه کردن درخواست، و بیان چیزی که واقعی نیست («اگر…»).",
         "would"),
    pattern([("Ik", "subject"), ("zou", "zou"), ("graag", "graag"),
             ("een afspraak", "object"), ("willen maken", "infinitives")],
            "«Ik zou graag … willen» رسمی‌ترین و مؤدبانه‌ترین شکل درخواست است."),
    [
        ex("Ik zou graag een afspraak maken.", "می‌خواستم یک قرار بگذارم."),
        ex("Zou u mij kunnen helpen?", "می‌شود کمکم کنید؟", "مؤدبانه‌ترین شکل درخواست"),
        ex("Dat zou fijn zijn.", "خیلی خوب می‌شد."),
        ex("Als ik meer tijd had, zou ik meer sporten.", "اگر وقت بیشتری داشتم، بیشتر ورزش می‌کردم."),
        ex("Ik zou het anders doen.", "من جور دیگری انجامش می‌دادم.", "نظر دادن محتاطانه"),
    ],
    [
        wrong("Ik wil een afspraak maken. (aan de telefoon, formeel)",
              "Ik zou graag een afspraak willen maken.",
              "«Ik wil» در موقعیت رسمی خشک و کمی بی‌ادبانه است."),
        wrong("Als ik rijk ben, zou ik een huis kopen.",
              "Als ik rijk was, zou ik een huis kopen.",
              "در فرض غیرواقعی، جمله‌واره ماضی ساده می‌گیرد."),
    ],
    "در تلفن زدن به اداره، ایمیل کاری و مصاحبه، zou تفاوت بین «خواستن» و «درخواست مؤدبانه» است. یکی از پرکاربردترین کلمات در هلندیِ رسمی.",
    [
        mc("___ u mij kunnen helpen?", ["Zou", "Wil", "Kan"], "Zou",
           "zou مؤدبانه‌ترین شکل است.", concept=C_ZOU),
        mc("Ik ___ graag een afspraak maken.", ["zou", "wil", "ga"], "zou",
           "«Ik zou graag…» شکل رسمی و مؤدبانه است.", concept=C_ZOU),
        mc("Als ik meer tijd ___, zou ik meer lezen.", ["had", "heb", "zou hebben"], "had",
           "در فرض غیرواقعی، جمله‌واره ماضی ساده می‌گیرد.", concept=C_ZOU),
        order("Ik zou graag een afspraak maken.",
              why="zou جای دوم، مصدر آخر.", concept=C_ZOU),
        transform("Ik wil je spreken. → (مؤدبانه با zou)",
                  "Ik zou je graag willen spreken.",
                  "zou + graag + مصدرها در انتها.", concept=C_ZOU),
        fix("Ik wil graag informatie over de cursus. (formele e-mail)",
            "Ik zou graag informatie over de cursus willen ontvangen.",
            "در ایمیل رسمی شکل zou … willen طبیعی‌تر است.", concept=C_ZOU),
        fa2nl("«می‌شود کمکم کنید؟» (خیلی مؤدبانه)", "Zou u mij kunnen helpen?",
              "zou + u + مصدرها.", concept=C_ZOU),
        scenario("Je belt een tandarts om een afspraak te maken.",
                 "Wat zeg je?",
                 ["Ik zou graag een afspraak willen maken.",
                  "Ik wil een afspraak maken.",
                  "Ik maak een afspraak."],
                 "Ik zou graag een afspraak willen maken.",
                 "در تماس رسمی، شکل zou … willen مؤدبانه‌ترین است.", concept=C_ZOU),
    ])

lesson(
    "b1-l12", "b1-conditioneel", "B1",
    "Als ik jou was", "جمله‌ی شرطی",
    [C_ALS_DAN, C_ZOU],
    discover(
        ["Als het regent, blijf ik thuis.",
         "Als ik tijd had, zou ik komen.",
         "Als ik jou was, zou ik het vragen."],
        "کدام‌شان ممکن است و کدام فقط یک فرض است؟",
        "اولی واقعی است (زمان حال). دومی و سومی فرضی‌اند: جمله‌واره ماضی ساده می‌گیرد و جمله‌ی اصلی zou."),
    rule("echt: als + presens · onwerkelijk: als + verleden tijd, … zou",
         "«Als ik jou was» عبارت ثابت برای نصیحت کردن است.",
         "if I were you"),
    pattern([("Als ik jou was", "condition"), (",", "comma"), ("zou", "zou"),
             ("ik", "subject"), ("het vragen", "rest")],
            "بعد از کاما، فعل جمله‌ی اصلی اول می‌آید — همان قانون همیشگی."),
    [
        ex("Als je vragen hebt, bel me gerust.", "اگر سؤالی داشتی، راحت زنگ بزن."),
        ex("Als ik jou was, zou ik het gewoon vragen.", "اگر جای تو بودم، همین‌طوری می‌پرسیدم."),
        ex("Als ik meer verdiende, zou ik verhuizen.", "اگر بیشتر درمی‌آوردم، اسباب‌کشی می‌کردم."),
        ex("Als het morgen mooi weer is, gaan we fietsen.", "اگر فردا هوا خوب باشد، دوچرخه‌سواری می‌رویم."),
    ],
    [
        wrong("Als ik jou ben, zou ik het vragen.", "Als ik jou was, zou ik het vragen.",
              "در فرض غیرواقعی، جمله‌واره ماضی ساده می‌گیرد."),
        wrong("Als ik tijd zou hebben, zou ik komen. (te zwaar)",
              "Als ik tijd had, zou ik komen.",
              "دو تا zou در یک جمله سنگین است؛ در جمله‌واره ماضی ساده کافی است."),
    ],
    "برای نصیحت کردن، مذاکره و توضیح دادن گزینه‌ها. «Als ik jou was…» مؤدبانه‌ترین راه توصیه کردن است، چون مستقیم دستور نمی‌دهی.",
    [
        mc("Als ik jou ___, zou ik het vragen.", ["was", "ben", "zou zijn"], "was",
           "فرض غیرواقعی → ماضی ساده در جمله‌واره.", concept=C_ALS_DAN),
        pickorder("کدام درست است؟",
                  ["Als het regent, blijf ik thuis.", "Als het regent, ik blijf thuis."],
                  "Als het regent, blijf ik thuis.",
                  "بعد از جمله‌واره‌ی اول، فعل جمله‌ی اصلی می‌آید.", concept=C_ALS_DAN),
        mc("Als ik meer tijd had, ___ ik meer sporten.", ["zou", "zal", "ga"], "zou",
           "در جمله‌ی اصلیِ فرض غیرواقعی zou می‌آید.", concept=C_ALS_DAN),
        order("Als je vragen hebt, bel me gerust.",
              why="جمله‌واره اول، بعد فعل امری.", concept=C_ALS_DAN),
        transform("Ik heb geen tijd, dus ik kom niet. → (فرضی با «als»)",
                  "Als ik tijd had, zou ik komen.",
                  "ماضی ساده در جمله‌واره + zou در جمله‌ی اصلی.", concept=C_ALS_DAN),
        fix("Als ik jou ben, ik zou het vragen.", "Als ik jou was, zou ik het vragen.",
            "هم ماضی ساده لازم است و هم بعد از کاما فعل اول می‌آید.", concept=C_ALS_DAN),
        fa2nl("«اگر جای تو بودم، می‌پرسیدم.»", "Als ik jou was, zou ik het vragen.",
              "عبارت ثابت «Als ik jou was».", concept=C_ALS_DAN),
        scenario("Je collega twijfelt of hij om opslag zal vragen.",
                 "Wat zeg je als advies?",
                 ["Als ik jou was, zou ik het gewoon vragen.",
                  "Als ik jou ben, vraag ik het.",
                  "Als ik was jou, zou het vragen."],
                 "Als ik jou was, zou ik het gewoon vragen.",
                 "نصیحت مؤدبانه با «Als ik jou was, zou ik…».", concept=C_ALS_DAN),
    ])

lesson(
    "b1-l13", "b1-nuance", "B1",
    "Even, maar, toch, wel", "کلمات کوچکی که لحن را می‌سازند",
    [C_PARTICLE],
    discover(
        ["Kom je?  →  Kom je even?", "Doe het.  →  Doe het maar.",
         "Ik weet het niet.  →  Ik weet het toch niet.",
         "Dat is leuk.  →  Dat is wel leuk."],
        "معنی جمله‌ها عوض شد یا چیز دیگری؟",
        "معنی تقریباً همان است — لحن عوض شد. این کلمه‌ها جمله را نرم، دوستانه یا محتاط می‌کنند."),
    rule("even = kort · maar = geruststellend · toch = tegen verwachting · wel = wél/redelijk",
         "بدون این کلمه‌ها هلندی‌ات درست ولی خشک است. با آن‌ها ناگهان طبیعی می‌شود.",
         "little words that carry tone"),
    pattern([("Doe", "verb"), ("het", "object"), ("maar", "particle"), ("→", "arrow"),
             ("«راحت باش، انجامش بده»", "meaning")],
            "«hoor» هم در آخر جمله لحن را دوستانه می‌کند: Dat is goed hoor."),
    [
        ex("Kun je even helpen?", "می‌شود یک لحظه کمک کنی؟", "even = کوتاه و بی‌زحمت"),
        ex("Ga maar zitten.", "بفرمایید بنشینید.", "maar = خیالت راحت"),
        ex("Het is toch gelukt.", "بالاخره درست شد.", "toch = برخلاف انتظار"),
        ex("Dat is wel lekker.", "راستش خوشمزه است.", "wel = تأیید ملایم"),
        ex("Kom eens langs!", "یک سر بیا!", "eens = دعوت غیررسمی"),
        ex("Dat klopt hoor.", "درست است ها.", "hoor = دوستانه و بی‌تنش"),
    ],
    [
        wrong("Help mij.", "Kun je me even helpen?",
              "بدون even و بدون سؤال، درخواست خشن به نظر می‌رسد."),
        wrong("Zit.", "Ga maar zitten.",
              "«Zit» دستور خشک است؛ با maar به تعارف تبدیل می‌شود."),
    ],
    "این کلمه‌ها همان چیزی هستند که هلندی‌ات را از «درست» به «طبیعی» می‌برند. در محیط کار و بین دوستان بی‌وقفه شنیده می‌شوند.",
    [
        mc("Kun je me ___ helpen? (vriendelijk, kort)", ["even", "toch", "wel"], "even",
           "even یعنی «یک لحظه» و درخواست را سبک می‌کند.", concept=C_PARTICLE),
        mc("Ga ___ zitten. (gastvrij)", ["maar", "even", "toch"], "maar",
           "maar در تعارف یعنی «راحت باش».", concept=C_PARTICLE),
        mc("Het is ___ gelukt! (tegen de verwachting in)", ["toch", "maar", "even"], "toch",
           "toch یعنی برخلاف انتظار.", concept=C_PARTICLE),
        blank("Kom ___ langs, gezellig! (uitnodiging)", "eens",
              "eens دعوت را غیررسمی و گرم می‌کند.", concept=C_PARTICLE),
        pick2("Dat is ___ lekker. (milde bevestiging)", ["wel", "even"], "wel",
              "wel تأیید ملایم است.", concept=C_PARTICLE),
        fix("Help mij met deze tas.", "Kun je me even helpen met deze tas?",
            "با سؤال و even درخواست مؤدبانه می‌شود.", concept=C_PARTICLE),
        fa2nl("«می‌شود یک لحظه کمکم کنی؟»", "Kun je me even helpen?",
              "even لحن را سبک می‌کند.", concept=C_PARTICLE),
        scenario("Een collega verontschuldigt zich voor een kleine fout.",
                 "Wat zeg je om het luchtig te houden?",
                 ["Geeft niet hoor.", "Geeft niet.", "Niet geeft hoor."],
                 "Geeft niet hoor.",
                 "hoor در انتها جمله را گرم و بی‌تنش می‌کند.", concept=C_PARTICLE),
    ])

lesson(
    "b1-l14", "b1-nuance", "B1",
    "Hij zei dat hij later kwam", "نقل قول غیرمستقیم",
    [C_REPORTED],
    discover(
        ["«Ik kom later.»  →  Hij zei dat hij later kwam.",
         "«Kun je bellen?»  →  Ze vroeg of ik kon bellen."],
        "سه چیز عوض شد. کدام‌ها؟",
        "ضمیر (ik → hij)، زمان فعل (kom → kwam) و جای فعل (به آخر رفت). سؤال بله/خیر هم of گرفت."),
    rule("dat / of + bijzin · werkwoord achteraan · voornaamwoorden aanpassen",
         "اگر جمله‌ی اصلی گذشته باشد، فعلِ نقل‌شده هم معمولاً گذشته می‌شود.",
         "he said that…"),
    pattern([("Hij zei", "main"), ("dat", "conj"), ("hij", "pronoun"),
             ("later", "time"), ("kwam", "verb-end")],
            "«Volgens hem…» راه کوتاه‌تر و بسیار رایج برای همین کار است."),
    [
        ex("Hij zei dat hij later zou komen.", "گفت که دیرتر می‌آید."),
        ex("Ze vroeg of ik tijd had.", "پرسید که وقت دارم یا نه."),
        ex("Volgens mijn collega is de vergadering verzet.", "به گفته‌ی همکارم جلسه جابه‌جا شده."),
        ex("De dokter zei dat ik moest rusten.", "دکتر گفت باید استراحت کنم."),
        ex("Ik hoorde dat je een nieuwe baan hebt.", "شنیدم شغل جدیدی گرفته‌ای."),
    ],
    [
        wrong("Hij zei dat hij komt later.", "Hij zei dat hij later kwam.",
              "فعل جمله‌واره آخر می‌رود و با زمانِ جمله‌ی اصلی هماهنگ می‌شود."),
        wrong("Ze vroeg dat ik tijd had.", "Ze vroeg of ik tijd had.",
              "سؤال بله/خیر با of نقل می‌شود، نه با dat."),
    ],
    "در محل کار مدام لازم است: پیام رساندن، خلاصه‌ی جلسه، توضیح دادن اینکه دکتر یا اداره چه گفته.",
    [
        mc("Hij zei ___ hij later kwam.", ["dat", "of", "als"], "dat",
           "جمله‌ی خبری نقل‌شده با dat می‌آید.", concept=C_REPORTED),
        mc("Ze vroeg ___ ik tijd had.", ["of", "dat", "als"], "of",
           "سؤال بله/خیر نقل‌شده با of می‌آید.", concept=C_REPORTED),
        pickorder("کدام درست است؟",
                  ["Hij zei dat hij later kwam.", "Hij zei dat hij kwam later.",
                   "Hij zei dat kwam hij later."],
                  "Hij zei dat hij later kwam.",
                  "فعل آخرین کلمه‌ی جمله‌واره است.", concept=C_REPORTED),
        transform("«Ik kom morgen.» (Hij zei …) →", "Hij zei dat hij morgen kwam.", 
                  "ضمیر عوض می‌شود، فعل آخر می‌رود و به گذشته می‌رود.", alt=["Hij zei dat hij morgen zou komen."], concept=C_REPORTED),
        transform("«Heb je tijd?» (Ze vroeg …) →", "Ze vroeg of ik tijd had.",
                  "of + جمله‌واره با فعل آخر.", concept=C_REPORTED),
        subclause("De dokter zei dat ik moest rusten.",
                  why="dat + فاعل + بقیه + فعل آخر.", concept=C_REPORTED),
        fix("Mijn collega zei dat de vergadering is verzet.",
            "Mijn collega zei dat de vergadering verzet was.",
            "زمان با جمله‌ی اصلی هماهنگ می‌شود و فعل آخر می‌رود.", concept=C_REPORTED),
        fa2nl("«شنیدم که شغل جدیدی گرفته‌ای.»", "Ik hoorde dat je een nieuwe baan hebt.",
              "dat + جمله‌واره با فعل آخر.", concept=C_REPORTED),
    ])

lesson(
    "b1-l15", "b1-nuance", "B1",
    "Op het werk en in een sollicitatie", "عبارت‌های ثابت کار و مصاحبه",
    [C_WORK_PHRASES, C_ZOU],
    discover(
        ["Ik zou graag meer verantwoordelijkheid willen.",
         "Het lijkt me een mooie uitdaging.",
         "Ik ben benieuwd of er ruimte is voor groei."],
        "چه چیزی این جمله‌ها را حرفه‌ای می‌کند؟",
        "هیچ‌کدام مستقیم نیستند. هلندیِ کاری محتاط و غیرمستقیم است: zou، lijkt me، benieuwd."),
    rule("Ik zou graag … · Het lijkt me … · Ik ben benieuwd of … · Ik heb ervaring met …",
         "این‌ها را مثل واژه حفظ کن، نه مثل دستور زبان. در مصاحبه و ایمیل بلافاصله به کار می‌آیند.",
         "professional set phrases"),
    pattern([("Het lijkt me", "phrase"), ("een mooie kans", "object"),
             ("|", "sep"), ("Ik ben benieuwd", "phrase"), ("of …", "clause")],
            "«Het lijkt me…» یعنی «به نظرم…» ولی نرم‌تر و کم‌ادعاتر."),
    [
        ex("Ik heb drie jaar ervaring met projectmanagement.", "سه سال تجربه‌ی مدیریت پروژه دارم."),
        ex("Het lijkt me een mooie uitdaging.", "به نظرم چالش خوبی است."),
        ex("Ik zou graag willen weten hoe het team werkt.", "دوست دارم بدانم تیم چطور کار می‌کند."),
        ex("Ik ben benieuwd of er doorgroeimogelijkheden zijn.", "کنجکاوم بدانم امکان رشد هست یا نه."),
        ex("Zou het mogelijk zijn om vrijdag thuis te werken?", "امکانش هست جمعه‌ها خانه کار کنم؟"),
        ex("Ik hoor graag van u.", "منتظر خبرتان هستم.", "پایان استاندارد ایمیل رسمی"),
    ],
    [
        wrong("Ik wil meer geld.", "Ik zou graag willen praten over mijn salaris.",
              "درخواست مستقیم درباره‌ی حقوق در هلند خام به نظر می‌رسد؛ با zou نرم‌ترش کن."),
        wrong("Ik ben goed in alles.", "Ik heb veel ervaring met …",
              "هلندی‌ها ادعای کلی را دوست ندارند؛ بهتر است مشخص و مستند حرف بزنی."),
    ],
    "دقیقاً در مصاحبه‌ی کاری، ارزیابی سالانه و ایمیل رسمی. این جمله‌ها را می‌شود آماده حفظ کرد و همان‌جا به کار برد.",
    [
        mc("___ me een mooie uitdaging.", ["Het lijkt", "Ik denk", "Ik vind het"], "Het lijkt",
           "«Het lijkt me…» شکل نرم و حرفه‌ای نظر دادن است.", concept=C_WORK_PHRASES),
        mc("Ik ben ___ of er ruimte is voor groei.",
           ["benieuwd", "nieuwsgierig dat", "benieuwd dat"], "benieuwd",
           "«benieuwd of» ساختار ثابت است.", concept=C_WORK_PHRASES),
        mc("Ik heb drie jaar ervaring ___ projectmanagement.", ["met", "in", "van"], "met",
           "«ervaring met» عبارت ثابت است.", concept=C_WORK_PHRASES),
        order("Ik zou graag meer verantwoordelijkheid willen.",
              why="zou جای دوم، مصدر willen در انتها.", concept=C_WORK_PHRASES),
        blank("___ het mogelijk zijn om vrijdag thuis te werken?", "Zou",
              "برای درخواست مؤدبانه: «Zou het mogelijk zijn om … te …?»", concept=C_WORK_PHRASES),
        fix("Ik wil praten over mijn salaris. (in een gesprek met je manager)",
            "Ik zou graag willen praten over mijn salaris.",
            "با zou درخواست حرفه‌ای‌تر می‌شود.", concept=C_WORK_PHRASES),
        fa2nl("«سه سال تجربه‌ی کار با مشتری دارم.»",
              "Ik heb drie jaar ervaring met klanten.",
              "ervaring met + اسم.", concept=C_WORK_PHRASES),
        scenario("Aan het eind van een sollicitatiegesprek mag je een vraag stellen.",
                 "Wat zeg je?",
                 ["Ik ben benieuwd hoe het team is samengesteld.",
                  "Ik wil weten hoe is het team.",
                  "Ik ben benieuwd hoe is het team samengesteld."],
                 "Ik ben benieuwd hoe het team is samengesteld.",
                 "بعد از benieuwd جمله‌واره می‌آید و فعلش آخر می‌رود.", concept=C_WORK_PHRASES),
    ])

# ----------------------------------------------------------------- modules

module("b1-werkwoordgroep", "B1", "Werkwoordgroepen", "خوشه‌های فعلی",
       "چند فعل در انتهای جمله، laten، hoeven و «aan het» — جایی که هلندی واقعاً پیچیده می‌شود.",
       ["b1-l07", "b1-l08", "b1-l09", "b1-l10"], icon="cards")

module("b1-conditioneel", "B1", "Zou en voorwaarden", "شرط و ادب",
       "مؤدبانه درخواست کنی، نصیحت کنی و درباره‌ی چیزهای فرضی حرف بزنی.",
       ["b1-l11", "b1-l12"], icon="target")

module("b1-nuance", "B1", "Natuurlijk klinken", "طبیعی حرف زدن",
       "کلمات کوچکِ لحن‌ساز، نقل قول، و عبارت‌های آماده‌ی محیط کار و مصاحبه.",
       ["b1-l13", "b1-l14", "b1-l15"], icon="user")
